---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/scm-tag: HEAD
      fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/poc-onboarding-app-service
    labels:
      app: poc-onboarding-app-service
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: com.ljdynamics
    name: poc-onboarding-app-service
  spec:
    ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      app: poc-onboarding-app-service
      provider: fabric8
      group: com.ljdynamics
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=poc-onboarding-app-service&var-version=1.0-SNAPSHOT
      fabric8.io/scm-tag: HEAD
      fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/poc-onboarding-app-service
    labels:
      app: poc-onboarding-app-service
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: com.ljdynamics
    name: poc-onboarding-app-service
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: poc-onboarding-app-service
        provider: fabric8
        group: com.ljdynamics
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: img/icons/spring-boot.svg
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=poc-onboarding-app-service&var-version=1.0-SNAPSHOT
          fabric8.io/scm-tag: HEAD
          fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/poc-onboarding-app-service
        labels:
          app: poc-onboarding-app-service
          provider: fabric8
          version: 1.0-SNAPSHOT
          group: com.ljdynamics
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: apps/poc-onboarding-app-service:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: apps-poc-onboarding-app-service
          ports:
          - containerPort: 8090
            protocol: TCP
          securityContext:
            privileged: false
