---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/poc-onboarding-app-service
  labels:
    app: poc-onboarding-app-service
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: com.ljdynamics
  name: poc-onboarding-app-service
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: poc-onboarding-app-service
    provider: fabric8
    group: com.ljdynamics
